---
#######################################################################################################################
# Networks
#######################################################################################################################
networks:
  mailserver:
    name: mailserver

#######################################################################################################################
# Volumes
#######################################################################################################################
volumes:
  mailserver-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "../data/mailserver/data"
  mailserver-state:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "../data/mailserver/state"
  mailserver-logs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "../data/mailserver/logs"
  mailserver-config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "../data/mailserver/config"

#######################################################################################################################
# Services
#######################################################################################################################
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    # hostname: ${DOMAIN}
    networks:
      - mailserver
    env_file: ../data/mailserver/mailserver.env
    environment:
      # IMPORTANT! check openralay on an external IP!
      PERMIT_DOCKER: connected-networks
      OVERRIDE_HOSTNAME: ${DOMAIN}
      SSL_TYPE: letsencrypt
      SSL_DOMAIN: ${DOMAIN}
    ports:
      - "${MAILSERVER_EXTERNAL_IP_25:-127.0.0.1}:25:25"     # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "${MAILSERVER_EXTERNAL_IP_143:-127.0.0.1}:143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "${MAILSERVER_EXTERNAL_IP_465:-127.0.0.1}:465:465"  # ESMTP (implicit TLS)
      - "${MAILSERVER_EXTERNAL_IP_587:-127.0.0.1}:587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "${MAILSERVER_EXTERNAL_IP_993:-127.0.0.1}:993:993"  # IMAP4 (implicit TLS)
    volumes:
      - acme:/etc/letsencrypt
      - mailserver-data:/var/mail/
      - mailserver-state:/var/mail-state/
      - mailserver-logs:/var/log/mail/
      - mailserver-config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      # retries: 0
